import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  cssValue,
  cssVariableName,
  loadThemeEntries,
  readJson,
  validateTokenEntries,
} from '../lib/token-core.mjs';

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const sourceRoot = path.join(packageRoot, 'src');
const outputRoot = path.join(packageRoot, 'dist');
const contract = await readJson(
  path.join(sourceRoot, 'contracts/theme-contract.json'),
);
const generated = {};

for (const theme of contract.themes) {
  const result = validateTokenEntries(
    await loadThemeEntries(sourceRoot, theme),
    contract,
  );
  if (result.errors.length || !result.resolved)
    throw new Error(result.errors.join('\n'));
  generated[theme] = Object.fromEntries(
    [...result.map.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, entry]) => [
        name,
        { type: entry.token.$type, value: result.resolved.get(name) },
      ]),
  );
}

await rm(outputRoot, { recursive: true, force: true });
for (const directory of ['css', 'json', 'typescript', 'tailwind'])
  await mkdir(path.join(outputRoot, directory), { recursive: true });

const banner = '/* Generated by @interfaceos/tokens. Do not edit. */';
const cssBlocks = Object.entries(generated).map(([theme, tokens]) => {
  const selector =
    theme === 'light'
      ? ":root, [data-theme='light']"
      : `[data-theme='${theme}']`;
  const declarations = Object.entries(tokens)
    .map(
      ([name, token]) =>
        `  ${cssVariableName(name)}: ${cssValue(token.value, token.type)};`,
    )
    .join('\n');
  return `${selector} {\n${declarations}\n}`;
});
await writeFile(
  path.join(outputRoot, 'css/tokens.css'),
  `${banner}\n${cssBlocks.join('\n\n')}\n`,
);

for (const [theme, tokens] of Object.entries(generated)) {
  await writeFile(
    path.join(outputRoot, `json/tokens.${theme}.json`),
    `${JSON.stringify(tokens, null, 2)}\n`,
  );
}

const typescript = `// Generated by @interfaceos/tokens. Do not edit.\nexport const tokens = ${JSON.stringify(generated, null, 2)} as const;\nexport type InterfaceOSTheme = keyof typeof tokens;\nexport type InterfaceOSTokenName = keyof typeof tokens.light;\n`;
await writeFile(path.join(outputRoot, 'typescript/tokens.ts'), typescript);

const tailwindTokens = Object.keys(generated.light).filter(
  (name) =>
    name.startsWith('color.semantic.') || name.startsWith('spacing.primitive.'),
);
const tailwind = tailwindTokens
  .map((name) => {
    const prefix = name.startsWith('color.semantic.')
      ? '--color-ios-'
      : '--spacing-ios-';
    const suffix = name
      .replace(/^color\.semantic\.|^spacing\.primitive\./, '')
      .replaceAll('.', '-');
    return `  ${prefix}${suffix}: var(${cssVariableName(name)});`;
  })
  .join('\n');
await writeFile(
  path.join(outputRoot, 'tailwind/theme.css'),
  `${banner}\n@theme inline {\n${tailwind}\n}\n`,
);

console.log(
  `Built ${Object.keys(generated.light).length} resolved tokens for ${contract.themes.length} themes.`,
);
